[package]
name = "rvn_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
include_dir = "0.7"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
rvn_bevy = { path = "../rvn_bevy" }
rvn_core = { path = "../rvn_core" }
rvn_parser = { path = "../rvn_parser" }
rvn_graph = { path = "../rvn_graph" }
rvn_ui = { path = "../rvn_ui" }
notify = "6"
owo-colors = "4.2"

[[bin]]
name = "rvn"
path = "src/main.rs"
